INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'LARANJA','VOLKSWAGEN','PASSAT LS','CEV8187','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'MARROM','VOLKSWAGEN','POINTER GLI 1.8','FIL5249','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERDE','VOLKSWAGEN','POLO 2.0 MI','FKK8368','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'LARANJA','VOLKSWAGEN','VOYAGE I MOTION','BKA3037','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'BEGE','TOYOTA','HILUX','CGZ3771','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'AZUL','TOYOTA','COROLLA','DMN3843','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'BEGE','HONDA','CIVIC','FOT4936','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'AMARELO','CHEVROLET','ZAFIRA 2.0','DEN2A34','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'PRATA','FORD','ESCORT L/LX 1.6','CBZ7048','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHO','FIAT','BRAVO ABSOLUTE','CWS1100','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHO','HONDA','CG 160','CAS3073','CARRO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'BRANCA','HONDA','BIZ','FZD2299','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHA','HONDA','NXR160','BKM5969','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHA','HONDA','POP','BOK0898','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHA','HONDA','CB250F','GAF7153','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'PRETA','HONDA','PCX150','GCB0305','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHA','YAMAHA','FAZER250','BMN8033','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHA','YAMAHA','YBR 150','GEW9216','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'BRANCA','YAMAHA','XTZ 150','EIL6488','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'VERMELHA','HONDA','XRE 300','CIK6688','MOTO');
INSERT INTO estacionamentoteste (id,cor,marca,modelo,placa,tipo) VALUES (null,'BRANCO','CHECROLET','ONYX','CAB1F43','CARRO');